import Head from 'next/head'
import Layout from "@/components/layout"
import HeroImage from '@/components/hero-image';
import Desc from '@/components/desc';
import TechList from '@/components/tech-list';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
       <div className="flex flex-col gap-4">
       <HeroImage/>
        <Desc/>
        <TechList/>
        </div> 


      </Layout>
    </>
  )
}
